[package]
name = "mitm-scheduler-server"
version = "2.0.0"
edition = "2024"
license = "Apache-2.0"
description = "MitM scheduler server - core layer"
homepage = "https://github.com/Zheng-Bote/mitm-3"
repository = "https://github.com/Zheng-Bote/mitm-3/release/latest"
documentation = "https://github.com/Zheng-Bote/mitm-3/docs"
keywords = ["mitm-3", "core-layer"]

[dependencies]
